//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.14.0
//     from Assets/Project/Player/Controls.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

/// <summary>
/// Provides programmatic access to <see cref="InputActionAsset" />, <see cref="InputActionMap" />, <see cref="InputAction" /> and <see cref="InputControlScheme" /> instances defined in asset "Assets/Project/Player/Controls.inputactions".
/// </summary>
/// <remarks>
/// This class is source generated and any manual edits will be discarded if the associated asset is reimported or modified.
/// </remarks>
/// <example>
/// <code>
/// using namespace UnityEngine;
/// using UnityEngine.InputSystem;
///
/// // Example of using an InputActionMap named "Player" from a UnityEngine.MonoBehaviour implementing callback interface.
/// public class Example : MonoBehaviour, MyActions.IPlayerActions
/// {
///     private MyActions_Actions m_Actions;                  // Source code representation of asset.
///     private MyActions_Actions.PlayerActions m_Player;     // Source code representation of action map.
///
///     void Awake()
///     {
///         m_Actions = new MyActions_Actions();              // Create asset object.
///         m_Player = m_Actions.Player;                      // Extract action map object.
///         m_Player.AddCallbacks(this);                      // Register callback interface IPlayerActions.
///     }
///
///     void OnDestroy()
///     {
///         m_Actions.Dispose();                              // Destroy asset object.
///     }
///
///     void OnEnable()
///     {
///         m_Player.Enable();                                // Enable all actions within map.
///     }
///
///     void OnDisable()
///     {
///         m_Player.Disable();                               // Disable all actions within map.
///     }
///
///     #region Interface implementation of MyActions.IPlayerActions
///
///     // Invoked when "Move" action is either started, performed or canceled.
///     public void OnMove(InputAction.CallbackContext context)
///     {
///         Debug.Log($"OnMove: {context.ReadValue&lt;Vector2&gt;()}");
///     }
///
///     // Invoked when "Attack" action is either started, performed or canceled.
///     public void OnAttack(InputAction.CallbackContext context)
///     {
///         Debug.Log($"OnAttack: {context.ReadValue&lt;float&gt;()}");
///     }
///
///     #endregion
/// }
/// </code>
/// </example>
public partial class @Controls: IInputActionCollection2, IDisposable
{
    /// <summary>
    /// Provides access to the underlying asset instance.
    /// </summary>
    public InputActionAsset asset { get; }

    /// <summary>
    /// Constructs a new instance.
    /// </summary>
    public @Controls()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""Controls"",
    ""maps"": [
        {
            ""name"": ""Head"",
            ""id"": ""2b37adaa-baed-41a5-a66e-81f61f2fd262"",
            ""actions"": [
                {
                    ""name"": ""Pos"",
                    ""type"": ""Value"",
                    ""id"": ""abb3f581-54cc-487a-bdc4-3206ec6c3aac"",
                    ""expectedControlType"": ""Vector3"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Rot"",
                    ""type"": ""Value"",
                    ""id"": ""5b7fb561-8904-4fdc-8966-64ccaf1ed21e"",
                    ""expectedControlType"": ""Quaternion"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Alive"",
                    ""type"": ""Button"",
                    ""id"": ""739587db-c697-485f-aaa8-6eae605f8f35"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""bac44c05-31e0-4a6d-a3ff-b89b85284535"",
                    ""path"": ""<XRHMD>/centerEyePosition"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Pos"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8c0b3eb5-8a99-49ef-a09c-742725be9e3d"",
                    ""path"": ""<XRHMD>/centerEyeRotation"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Rot"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""bf757d24-797d-4a9d-9636-209b69170738"",
                    ""path"": ""<XRHMD>/userPresence"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Alive"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""LHand"",
            ""id"": ""60259ee8-809a-41e7-ac56-94a37235b085"",
            ""actions"": [
                {
                    ""name"": ""Pos"",
                    ""type"": ""Value"",
                    ""id"": ""7a6eca80-9e09-41bf-9379-cbc41c000028"",
                    ""expectedControlType"": ""Vector3"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Rot"",
                    ""type"": ""PassThrough"",
                    ""id"": ""874028ab-df1c-41a8-8f4c-0629dacfa0cc"",
                    ""expectedControlType"": ""Quaternion"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Stick"",
                    ""type"": ""Value"",
                    ""id"": ""84e571ca-0684-4b22-903b-02ac1ac01ff3"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""StickButton"",
                    ""type"": ""Button"",
                    ""id"": ""e7d3fbef-56de-4803-9900-102c27861f7c"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Grip"",
                    ""type"": ""Value"",
                    ""id"": ""d2585f05-7de2-4ca0-a2da-38538f5945f6"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Trigger"",
                    ""type"": ""Value"",
                    ""id"": ""d756aaff-eb3b-47b3-ae5d-bb893ef576cc"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""NearButton"",
                    ""type"": ""Button"",
                    ""id"": ""bc153d76-b359-4eba-aa6f-66cd3282f10e"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""FarButton"",
                    ""type"": ""Button"",
                    ""id"": ""7569f0ed-79ac-4e03-bd8e-77c11b3b2ae3"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Alive"",
                    ""type"": ""Button"",
                    ""id"": ""deefc3b9-f366-422b-a746-1f9197e951c4"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""e2549898-51c4-4755-8c5b-938cd5794053"",
                    ""path"": ""<XRController>{LeftHand}/devicePosition"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Pos"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0361cadd-f98c-4dd7-b2cf-fb2d5dcbbd5a"",
                    ""path"": ""<XRController>{LeftHand}/deviceRotation"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Rot"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""74c49a82-7c5f-4076-9e30-348dfcfda932"",
                    ""path"": ""<XRController>{LeftHand}/joystick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Stick"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""29038248-3464-4b3a-a8df-09c2a80d67b2"",
                    ""path"": ""<XRController>{LeftHand}/trigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Trigger"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6837f62b-a41e-440b-8d66-cd3cb8331731"",
                    ""path"": ""<XRController>{LeftHand}/grip"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Grip"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2ce98caa-877d-40ea-954e-aaf7463ff801"",
                    ""path"": ""<XRController>{LeftHand}/secondaryButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""FarButton"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""bfa7dedf-b920-4069-825a-3f0e66c58803"",
                    ""path"": ""<XRController>{LeftHand}/primaryButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""NearButton"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""98a633c6-0629-4113-ae52-2e3e2e7eec29"",
                    ""path"": ""<XRController>{LeftHand}/isTracked"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Alive"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d65a4a0f-6eed-49db-a8d4-6ce6ce612a20"",
                    ""path"": ""<XRController>{LeftHand}/joystickClicked"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""StickButton"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""RHand"",
            ""id"": ""dd6bd3f5-04ba-4901-bc43-7267c4d972bc"",
            ""actions"": [
                {
                    ""name"": ""Pos"",
                    ""type"": ""Value"",
                    ""id"": ""67030ed7-c091-4aab-8730-db7f02262b0b"",
                    ""expectedControlType"": ""Vector3"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Rot"",
                    ""type"": ""Value"",
                    ""id"": ""70ef6188-a8bc-4c98-a69a-db5f4556d1f7"",
                    ""expectedControlType"": ""Quaternion"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Stick"",
                    ""type"": ""Value"",
                    ""id"": ""50032c42-c27b-4746-a234-841e3c30c95d"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""StickButton"",
                    ""type"": ""Button"",
                    ""id"": ""c1ff2d6e-be8c-4142-aa21-f6d9532200e5"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Grip"",
                    ""type"": ""Value"",
                    ""id"": ""665e213b-9389-44bf-aa8d-3d453b7e8b6a"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Trigger"",
                    ""type"": ""Value"",
                    ""id"": ""781e6d37-1c32-46b7-b4d3-45af61c0f0a9"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""NearButton"",
                    ""type"": ""Button"",
                    ""id"": ""4af8fc44-1f26-48ce-a5f7-4a8dbc0ba6ff"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""FarButton"",
                    ""type"": ""Button"",
                    ""id"": ""087b7597-4ad8-4e32-a9f9-bad5af54ccaf"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Alive"",
                    ""type"": ""Button"",
                    ""id"": ""7e436745-c6c7-4864-8147-42a675d17049"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""0453079c-73db-4ddb-97a2-2898ecd595e5"",
                    ""path"": ""<XRController>{RightHand}/devicePosition"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Pos"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""20403f62-9869-458d-a919-a156490699d0"",
                    ""path"": ""<XRController>{RightHand}/deviceRotation"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Rot"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""289b267d-d63c-4101-a620-2686aa751e1d"",
                    ""path"": ""<XRController>{RightHand}/joystick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Stick"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d47c11fc-2bb1-453f-b2e6-1e393fabb4f5"",
                    ""path"": ""<XRController>{RightHand}/grip"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Grip"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""60d1b3b3-3600-4a82-ac41-dc9ba06517b8"",
                    ""path"": ""<XRController>{RightHand}/trigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Trigger"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e8462793-9d50-4309-a3c6-da58c979da48"",
                    ""path"": ""<XRController>{RightHand}/secondaryButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""FarButton"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6bd57872-f084-4d20-b924-a5028b78a46f"",
                    ""path"": ""<XRController>{RightHand}/primaryButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""NearButton"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c8f0f407-2167-49ad-8cd1-16025e70b406"",
                    ""path"": ""<XRController>{RightHand}/isTracked"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Alive"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""485e9e66-3d2d-496c-bdb4-599f96c0a5cc"",
                    ""path"": ""<XRController>{RightHand}/joystickClicked"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""StickButton"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Head
        m_Head = asset.FindActionMap("Head", throwIfNotFound: true);
        m_Head_Pos = m_Head.FindAction("Pos", throwIfNotFound: true);
        m_Head_Rot = m_Head.FindAction("Rot", throwIfNotFound: true);
        m_Head_Alive = m_Head.FindAction("Alive", throwIfNotFound: true);
        // LHand
        m_LHand = asset.FindActionMap("LHand", throwIfNotFound: true);
        m_LHand_Pos = m_LHand.FindAction("Pos", throwIfNotFound: true);
        m_LHand_Rot = m_LHand.FindAction("Rot", throwIfNotFound: true);
        m_LHand_Stick = m_LHand.FindAction("Stick", throwIfNotFound: true);
        m_LHand_StickButton = m_LHand.FindAction("StickButton", throwIfNotFound: true);
        m_LHand_Grip = m_LHand.FindAction("Grip", throwIfNotFound: true);
        m_LHand_Trigger = m_LHand.FindAction("Trigger", throwIfNotFound: true);
        m_LHand_NearButton = m_LHand.FindAction("NearButton", throwIfNotFound: true);
        m_LHand_FarButton = m_LHand.FindAction("FarButton", throwIfNotFound: true);
        m_LHand_Alive = m_LHand.FindAction("Alive", throwIfNotFound: true);
        // RHand
        m_RHand = asset.FindActionMap("RHand", throwIfNotFound: true);
        m_RHand_Pos = m_RHand.FindAction("Pos", throwIfNotFound: true);
        m_RHand_Rot = m_RHand.FindAction("Rot", throwIfNotFound: true);
        m_RHand_Stick = m_RHand.FindAction("Stick", throwIfNotFound: true);
        m_RHand_StickButton = m_RHand.FindAction("StickButton", throwIfNotFound: true);
        m_RHand_Grip = m_RHand.FindAction("Grip", throwIfNotFound: true);
        m_RHand_Trigger = m_RHand.FindAction("Trigger", throwIfNotFound: true);
        m_RHand_NearButton = m_RHand.FindAction("NearButton", throwIfNotFound: true);
        m_RHand_FarButton = m_RHand.FindAction("FarButton", throwIfNotFound: true);
        m_RHand_Alive = m_RHand.FindAction("Alive", throwIfNotFound: true);
    }

    ~@Controls()
    {
        UnityEngine.Debug.Assert(!m_Head.enabled, "This will cause a leak and performance issues, Controls.Head.Disable() has not been called.");
        UnityEngine.Debug.Assert(!m_LHand.enabled, "This will cause a leak and performance issues, Controls.LHand.Disable() has not been called.");
        UnityEngine.Debug.Assert(!m_RHand.enabled, "This will cause a leak and performance issues, Controls.RHand.Disable() has not been called.");
    }

    /// <summary>
    /// Destroys this asset and all associated <see cref="InputAction"/> instances.
    /// </summary>
    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.bindingMask" />
    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.devices" />
    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.controlSchemes" />
    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Contains(InputAction)" />
    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.GetEnumerator()" />
    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    /// <inheritdoc cref="IEnumerable.GetEnumerator()" />
    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Enable()" />
    public void Enable()
    {
        asset.Enable();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Disable()" />
    public void Disable()
    {
        asset.Disable();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.bindings" />
    public IEnumerable<InputBinding> bindings => asset.bindings;

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.FindAction(string, bool)" />
    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.FindBinding(InputBinding, out InputAction)" />
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Head
    private readonly InputActionMap m_Head;
    private List<IHeadActions> m_HeadActionsCallbackInterfaces = new List<IHeadActions>();
    private readonly InputAction m_Head_Pos;
    private readonly InputAction m_Head_Rot;
    private readonly InputAction m_Head_Alive;
    /// <summary>
    /// Provides access to input actions defined in input action map "Head".
    /// </summary>
    public struct HeadActions
    {
        private @Controls m_Wrapper;

        /// <summary>
        /// Construct a new instance of the input action map wrapper class.
        /// </summary>
        public HeadActions(@Controls wrapper) { m_Wrapper = wrapper; }
        /// <summary>
        /// Provides access to the underlying input action "Head/Pos".
        /// </summary>
        public InputAction @Pos => m_Wrapper.m_Head_Pos;
        /// <summary>
        /// Provides access to the underlying input action "Head/Rot".
        /// </summary>
        public InputAction @Rot => m_Wrapper.m_Head_Rot;
        /// <summary>
        /// Provides access to the underlying input action "Head/Alive".
        /// </summary>
        public InputAction @Alive => m_Wrapper.m_Head_Alive;
        /// <summary>
        /// Provides access to the underlying input action map instance.
        /// </summary>
        public InputActionMap Get() { return m_Wrapper.m_Head; }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Enable()" />
        public void Enable() { Get().Enable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Disable()" />
        public void Disable() { Get().Disable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.enabled" />
        public bool enabled => Get().enabled;
        /// <summary>
        /// Implicitly converts an <see ref="HeadActions" /> to an <see ref="InputActionMap" /> instance.
        /// </summary>
        public static implicit operator InputActionMap(HeadActions set) { return set.Get(); }
        /// <summary>
        /// Adds <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <param name="instance">Callback instance.</param>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c> or <paramref name="instance"/> have already been added this method does nothing.
        /// </remarks>
        /// <seealso cref="HeadActions" />
        public void AddCallbacks(IHeadActions instance)
        {
            if (instance == null || m_Wrapper.m_HeadActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_HeadActionsCallbackInterfaces.Add(instance);
            @Pos.started += instance.OnPos;
            @Pos.performed += instance.OnPos;
            @Pos.canceled += instance.OnPos;
            @Rot.started += instance.OnRot;
            @Rot.performed += instance.OnRot;
            @Rot.canceled += instance.OnRot;
            @Alive.started += instance.OnAlive;
            @Alive.performed += instance.OnAlive;
            @Alive.canceled += instance.OnAlive;
        }

        /// <summary>
        /// Removes <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <remarks>
        /// Calling this method when <paramref name="instance" /> have not previously been registered has no side-effects.
        /// </remarks>
        /// <seealso cref="HeadActions" />
        private void UnregisterCallbacks(IHeadActions instance)
        {
            @Pos.started -= instance.OnPos;
            @Pos.performed -= instance.OnPos;
            @Pos.canceled -= instance.OnPos;
            @Rot.started -= instance.OnRot;
            @Rot.performed -= instance.OnRot;
            @Rot.canceled -= instance.OnRot;
            @Alive.started -= instance.OnAlive;
            @Alive.performed -= instance.OnAlive;
            @Alive.canceled -= instance.OnAlive;
        }

        /// <summary>
        /// Unregisters <param cref="instance" /> and unregisters all input action callbacks via <see cref="HeadActions.UnregisterCallbacks(IHeadActions)" />.
        /// </summary>
        /// <seealso cref="HeadActions.UnregisterCallbacks(IHeadActions)" />
        public void RemoveCallbacks(IHeadActions instance)
        {
            if (m_Wrapper.m_HeadActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        /// <summary>
        /// Replaces all existing callback instances and previously registered input action callbacks associated with them with callbacks provided via <param cref="instance" />.
        /// </summary>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c>, calling this method will only unregister all existing callbacks but not register any new callbacks.
        /// </remarks>
        /// <seealso cref="HeadActions.AddCallbacks(IHeadActions)" />
        /// <seealso cref="HeadActions.RemoveCallbacks(IHeadActions)" />
        /// <seealso cref="HeadActions.UnregisterCallbacks(IHeadActions)" />
        public void SetCallbacks(IHeadActions instance)
        {
            foreach (var item in m_Wrapper.m_HeadActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_HeadActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    /// <summary>
    /// Provides a new <see cref="HeadActions" /> instance referencing this action map.
    /// </summary>
    public HeadActions @Head => new HeadActions(this);

    // LHand
    private readonly InputActionMap m_LHand;
    private List<ILHandActions> m_LHandActionsCallbackInterfaces = new List<ILHandActions>();
    private readonly InputAction m_LHand_Pos;
    private readonly InputAction m_LHand_Rot;
    private readonly InputAction m_LHand_Stick;
    private readonly InputAction m_LHand_StickButton;
    private readonly InputAction m_LHand_Grip;
    private readonly InputAction m_LHand_Trigger;
    private readonly InputAction m_LHand_NearButton;
    private readonly InputAction m_LHand_FarButton;
    private readonly InputAction m_LHand_Alive;
    /// <summary>
    /// Provides access to input actions defined in input action map "LHand".
    /// </summary>
    public struct LHandActions
    {
        private @Controls m_Wrapper;

        /// <summary>
        /// Construct a new instance of the input action map wrapper class.
        /// </summary>
        public LHandActions(@Controls wrapper) { m_Wrapper = wrapper; }
        /// <summary>
        /// Provides access to the underlying input action "LHand/Pos".
        /// </summary>
        public InputAction @Pos => m_Wrapper.m_LHand_Pos;
        /// <summary>
        /// Provides access to the underlying input action "LHand/Rot".
        /// </summary>
        public InputAction @Rot => m_Wrapper.m_LHand_Rot;
        /// <summary>
        /// Provides access to the underlying input action "LHand/Stick".
        /// </summary>
        public InputAction @Stick => m_Wrapper.m_LHand_Stick;
        /// <summary>
        /// Provides access to the underlying input action "LHand/StickButton".
        /// </summary>
        public InputAction @StickButton => m_Wrapper.m_LHand_StickButton;
        /// <summary>
        /// Provides access to the underlying input action "LHand/Grip".
        /// </summary>
        public InputAction @Grip => m_Wrapper.m_LHand_Grip;
        /// <summary>
        /// Provides access to the underlying input action "LHand/Trigger".
        /// </summary>
        public InputAction @Trigger => m_Wrapper.m_LHand_Trigger;
        /// <summary>
        /// Provides access to the underlying input action "LHand/NearButton".
        /// </summary>
        public InputAction @NearButton => m_Wrapper.m_LHand_NearButton;
        /// <summary>
        /// Provides access to the underlying input action "LHand/FarButton".
        /// </summary>
        public InputAction @FarButton => m_Wrapper.m_LHand_FarButton;
        /// <summary>
        /// Provides access to the underlying input action "LHand/Alive".
        /// </summary>
        public InputAction @Alive => m_Wrapper.m_LHand_Alive;
        /// <summary>
        /// Provides access to the underlying input action map instance.
        /// </summary>
        public InputActionMap Get() { return m_Wrapper.m_LHand; }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Enable()" />
        public void Enable() { Get().Enable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Disable()" />
        public void Disable() { Get().Disable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.enabled" />
        public bool enabled => Get().enabled;
        /// <summary>
        /// Implicitly converts an <see ref="LHandActions" /> to an <see ref="InputActionMap" /> instance.
        /// </summary>
        public static implicit operator InputActionMap(LHandActions set) { return set.Get(); }
        /// <summary>
        /// Adds <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <param name="instance">Callback instance.</param>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c> or <paramref name="instance"/> have already been added this method does nothing.
        /// </remarks>
        /// <seealso cref="LHandActions" />
        public void AddCallbacks(ILHandActions instance)
        {
            if (instance == null || m_Wrapper.m_LHandActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_LHandActionsCallbackInterfaces.Add(instance);
            @Pos.started += instance.OnPos;
            @Pos.performed += instance.OnPos;
            @Pos.canceled += instance.OnPos;
            @Rot.started += instance.OnRot;
            @Rot.performed += instance.OnRot;
            @Rot.canceled += instance.OnRot;
            @Stick.started += instance.OnStick;
            @Stick.performed += instance.OnStick;
            @Stick.canceled += instance.OnStick;
            @StickButton.started += instance.OnStickButton;
            @StickButton.performed += instance.OnStickButton;
            @StickButton.canceled += instance.OnStickButton;
            @Grip.started += instance.OnGrip;
            @Grip.performed += instance.OnGrip;
            @Grip.canceled += instance.OnGrip;
            @Trigger.started += instance.OnTrigger;
            @Trigger.performed += instance.OnTrigger;
            @Trigger.canceled += instance.OnTrigger;
            @NearButton.started += instance.OnNearButton;
            @NearButton.performed += instance.OnNearButton;
            @NearButton.canceled += instance.OnNearButton;
            @FarButton.started += instance.OnFarButton;
            @FarButton.performed += instance.OnFarButton;
            @FarButton.canceled += instance.OnFarButton;
            @Alive.started += instance.OnAlive;
            @Alive.performed += instance.OnAlive;
            @Alive.canceled += instance.OnAlive;
        }

        /// <summary>
        /// Removes <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <remarks>
        /// Calling this method when <paramref name="instance" /> have not previously been registered has no side-effects.
        /// </remarks>
        /// <seealso cref="LHandActions" />
        private void UnregisterCallbacks(ILHandActions instance)
        {
            @Pos.started -= instance.OnPos;
            @Pos.performed -= instance.OnPos;
            @Pos.canceled -= instance.OnPos;
            @Rot.started -= instance.OnRot;
            @Rot.performed -= instance.OnRot;
            @Rot.canceled -= instance.OnRot;
            @Stick.started -= instance.OnStick;
            @Stick.performed -= instance.OnStick;
            @Stick.canceled -= instance.OnStick;
            @StickButton.started -= instance.OnStickButton;
            @StickButton.performed -= instance.OnStickButton;
            @StickButton.canceled -= instance.OnStickButton;
            @Grip.started -= instance.OnGrip;
            @Grip.performed -= instance.OnGrip;
            @Grip.canceled -= instance.OnGrip;
            @Trigger.started -= instance.OnTrigger;
            @Trigger.performed -= instance.OnTrigger;
            @Trigger.canceled -= instance.OnTrigger;
            @NearButton.started -= instance.OnNearButton;
            @NearButton.performed -= instance.OnNearButton;
            @NearButton.canceled -= instance.OnNearButton;
            @FarButton.started -= instance.OnFarButton;
            @FarButton.performed -= instance.OnFarButton;
            @FarButton.canceled -= instance.OnFarButton;
            @Alive.started -= instance.OnAlive;
            @Alive.performed -= instance.OnAlive;
            @Alive.canceled -= instance.OnAlive;
        }

        /// <summary>
        /// Unregisters <param cref="instance" /> and unregisters all input action callbacks via <see cref="LHandActions.UnregisterCallbacks(ILHandActions)" />.
        /// </summary>
        /// <seealso cref="LHandActions.UnregisterCallbacks(ILHandActions)" />
        public void RemoveCallbacks(ILHandActions instance)
        {
            if (m_Wrapper.m_LHandActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        /// <summary>
        /// Replaces all existing callback instances and previously registered input action callbacks associated with them with callbacks provided via <param cref="instance" />.
        /// </summary>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c>, calling this method will only unregister all existing callbacks but not register any new callbacks.
        /// </remarks>
        /// <seealso cref="LHandActions.AddCallbacks(ILHandActions)" />
        /// <seealso cref="LHandActions.RemoveCallbacks(ILHandActions)" />
        /// <seealso cref="LHandActions.UnregisterCallbacks(ILHandActions)" />
        public void SetCallbacks(ILHandActions instance)
        {
            foreach (var item in m_Wrapper.m_LHandActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_LHandActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    /// <summary>
    /// Provides a new <see cref="LHandActions" /> instance referencing this action map.
    /// </summary>
    public LHandActions @LHand => new LHandActions(this);

    // RHand
    private readonly InputActionMap m_RHand;
    private List<IRHandActions> m_RHandActionsCallbackInterfaces = new List<IRHandActions>();
    private readonly InputAction m_RHand_Pos;
    private readonly InputAction m_RHand_Rot;
    private readonly InputAction m_RHand_Stick;
    private readonly InputAction m_RHand_StickButton;
    private readonly InputAction m_RHand_Grip;
    private readonly InputAction m_RHand_Trigger;
    private readonly InputAction m_RHand_NearButton;
    private readonly InputAction m_RHand_FarButton;
    private readonly InputAction m_RHand_Alive;
    /// <summary>
    /// Provides access to input actions defined in input action map "RHand".
    /// </summary>
    public struct RHandActions
    {
        private @Controls m_Wrapper;

        /// <summary>
        /// Construct a new instance of the input action map wrapper class.
        /// </summary>
        public RHandActions(@Controls wrapper) { m_Wrapper = wrapper; }
        /// <summary>
        /// Provides access to the underlying input action "RHand/Pos".
        /// </summary>
        public InputAction @Pos => m_Wrapper.m_RHand_Pos;
        /// <summary>
        /// Provides access to the underlying input action "RHand/Rot".
        /// </summary>
        public InputAction @Rot => m_Wrapper.m_RHand_Rot;
        /// <summary>
        /// Provides access to the underlying input action "RHand/Stick".
        /// </summary>
        public InputAction @Stick => m_Wrapper.m_RHand_Stick;
        /// <summary>
        /// Provides access to the underlying input action "RHand/StickButton".
        /// </summary>
        public InputAction @StickButton => m_Wrapper.m_RHand_StickButton;
        /// <summary>
        /// Provides access to the underlying input action "RHand/Grip".
        /// </summary>
        public InputAction @Grip => m_Wrapper.m_RHand_Grip;
        /// <summary>
        /// Provides access to the underlying input action "RHand/Trigger".
        /// </summary>
        public InputAction @Trigger => m_Wrapper.m_RHand_Trigger;
        /// <summary>
        /// Provides access to the underlying input action "RHand/NearButton".
        /// </summary>
        public InputAction @NearButton => m_Wrapper.m_RHand_NearButton;
        /// <summary>
        /// Provides access to the underlying input action "RHand/FarButton".
        /// </summary>
        public InputAction @FarButton => m_Wrapper.m_RHand_FarButton;
        /// <summary>
        /// Provides access to the underlying input action "RHand/Alive".
        /// </summary>
        public InputAction @Alive => m_Wrapper.m_RHand_Alive;
        /// <summary>
        /// Provides access to the underlying input action map instance.
        /// </summary>
        public InputActionMap Get() { return m_Wrapper.m_RHand; }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Enable()" />
        public void Enable() { Get().Enable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Disable()" />
        public void Disable() { Get().Disable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.enabled" />
        public bool enabled => Get().enabled;
        /// <summary>
        /// Implicitly converts an <see ref="RHandActions" /> to an <see ref="InputActionMap" /> instance.
        /// </summary>
        public static implicit operator InputActionMap(RHandActions set) { return set.Get(); }
        /// <summary>
        /// Adds <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <param name="instance">Callback instance.</param>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c> or <paramref name="instance"/> have already been added this method does nothing.
        /// </remarks>
        /// <seealso cref="RHandActions" />
        public void AddCallbacks(IRHandActions instance)
        {
            if (instance == null || m_Wrapper.m_RHandActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_RHandActionsCallbackInterfaces.Add(instance);
            @Pos.started += instance.OnPos;
            @Pos.performed += instance.OnPos;
            @Pos.canceled += instance.OnPos;
            @Rot.started += instance.OnRot;
            @Rot.performed += instance.OnRot;
            @Rot.canceled += instance.OnRot;
            @Stick.started += instance.OnStick;
            @Stick.performed += instance.OnStick;
            @Stick.canceled += instance.OnStick;
            @StickButton.started += instance.OnStickButton;
            @StickButton.performed += instance.OnStickButton;
            @StickButton.canceled += instance.OnStickButton;
            @Grip.started += instance.OnGrip;
            @Grip.performed += instance.OnGrip;
            @Grip.canceled += instance.OnGrip;
            @Trigger.started += instance.OnTrigger;
            @Trigger.performed += instance.OnTrigger;
            @Trigger.canceled += instance.OnTrigger;
            @NearButton.started += instance.OnNearButton;
            @NearButton.performed += instance.OnNearButton;
            @NearButton.canceled += instance.OnNearButton;
            @FarButton.started += instance.OnFarButton;
            @FarButton.performed += instance.OnFarButton;
            @FarButton.canceled += instance.OnFarButton;
            @Alive.started += instance.OnAlive;
            @Alive.performed += instance.OnAlive;
            @Alive.canceled += instance.OnAlive;
        }

        /// <summary>
        /// Removes <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <remarks>
        /// Calling this method when <paramref name="instance" /> have not previously been registered has no side-effects.
        /// </remarks>
        /// <seealso cref="RHandActions" />
        private void UnregisterCallbacks(IRHandActions instance)
        {
            @Pos.started -= instance.OnPos;
            @Pos.performed -= instance.OnPos;
            @Pos.canceled -= instance.OnPos;
            @Rot.started -= instance.OnRot;
            @Rot.performed -= instance.OnRot;
            @Rot.canceled -= instance.OnRot;
            @Stick.started -= instance.OnStick;
            @Stick.performed -= instance.OnStick;
            @Stick.canceled -= instance.OnStick;
            @StickButton.started -= instance.OnStickButton;
            @StickButton.performed -= instance.OnStickButton;
            @StickButton.canceled -= instance.OnStickButton;
            @Grip.started -= instance.OnGrip;
            @Grip.performed -= instance.OnGrip;
            @Grip.canceled -= instance.OnGrip;
            @Trigger.started -= instance.OnTrigger;
            @Trigger.performed -= instance.OnTrigger;
            @Trigger.canceled -= instance.OnTrigger;
            @NearButton.started -= instance.OnNearButton;
            @NearButton.performed -= instance.OnNearButton;
            @NearButton.canceled -= instance.OnNearButton;
            @FarButton.started -= instance.OnFarButton;
            @FarButton.performed -= instance.OnFarButton;
            @FarButton.canceled -= instance.OnFarButton;
            @Alive.started -= instance.OnAlive;
            @Alive.performed -= instance.OnAlive;
            @Alive.canceled -= instance.OnAlive;
        }

        /// <summary>
        /// Unregisters <param cref="instance" /> and unregisters all input action callbacks via <see cref="RHandActions.UnregisterCallbacks(IRHandActions)" />.
        /// </summary>
        /// <seealso cref="RHandActions.UnregisterCallbacks(IRHandActions)" />
        public void RemoveCallbacks(IRHandActions instance)
        {
            if (m_Wrapper.m_RHandActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        /// <summary>
        /// Replaces all existing callback instances and previously registered input action callbacks associated with them with callbacks provided via <param cref="instance" />.
        /// </summary>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c>, calling this method will only unregister all existing callbacks but not register any new callbacks.
        /// </remarks>
        /// <seealso cref="RHandActions.AddCallbacks(IRHandActions)" />
        /// <seealso cref="RHandActions.RemoveCallbacks(IRHandActions)" />
        /// <seealso cref="RHandActions.UnregisterCallbacks(IRHandActions)" />
        public void SetCallbacks(IRHandActions instance)
        {
            foreach (var item in m_Wrapper.m_RHandActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_RHandActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    /// <summary>
    /// Provides a new <see cref="RHandActions" /> instance referencing this action map.
    /// </summary>
    public RHandActions @RHand => new RHandActions(this);
    /// <summary>
    /// Interface to implement callback methods for all input action callbacks associated with input actions defined by "Head" which allows adding and removing callbacks.
    /// </summary>
    /// <seealso cref="HeadActions.AddCallbacks(IHeadActions)" />
    /// <seealso cref="HeadActions.RemoveCallbacks(IHeadActions)" />
    public interface IHeadActions
    {
        /// <summary>
        /// Method invoked when associated input action "Pos" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnPos(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "Rot" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnRot(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "Alive" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnAlive(InputAction.CallbackContext context);
    }
    /// <summary>
    /// Interface to implement callback methods for all input action callbacks associated with input actions defined by "LHand" which allows adding and removing callbacks.
    /// </summary>
    /// <seealso cref="LHandActions.AddCallbacks(ILHandActions)" />
    /// <seealso cref="LHandActions.RemoveCallbacks(ILHandActions)" />
    public interface ILHandActions
    {
        /// <summary>
        /// Method invoked when associated input action "Pos" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnPos(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "Rot" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnRot(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "Stick" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnStick(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "StickButton" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnStickButton(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "Grip" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnGrip(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "Trigger" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnTrigger(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "NearButton" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnNearButton(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "FarButton" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnFarButton(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "Alive" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnAlive(InputAction.CallbackContext context);
    }
    /// <summary>
    /// Interface to implement callback methods for all input action callbacks associated with input actions defined by "RHand" which allows adding and removing callbacks.
    /// </summary>
    /// <seealso cref="RHandActions.AddCallbacks(IRHandActions)" />
    /// <seealso cref="RHandActions.RemoveCallbacks(IRHandActions)" />
    public interface IRHandActions
    {
        /// <summary>
        /// Method invoked when associated input action "Pos" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnPos(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "Rot" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnRot(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "Stick" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnStick(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "StickButton" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnStickButton(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "Grip" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnGrip(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "Trigger" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnTrigger(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "NearButton" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnNearButton(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "FarButton" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnFarButton(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "Alive" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnAlive(InputAction.CallbackContext context);
    }
}
