// Generated by Claude
using UnityEngine;

[System.Serializable] public struct JointDriveData {
	public float positionSpring;
	public float positionDamper;
	public float maximumForce;
	public bool useAcceleration;
	public static implicit operator JointDrive(JointDriveData d) => new() {
		positionSpring  = d.positionSpring,
		positionDamper  = d.positionDamper,
		maximumForce    = d.maximumForce,
		useAcceleration = d.useAcceleration
	};
	public static JointDriveData Lerp(JointDriveData a, JointDriveData b, float t) => new() {
		positionSpring  = Mathf.Lerp(a.positionSpring,  b.positionSpring,  t),
		positionDamper  = Mathf.Lerp(a.positionDamper,  b.positionDamper,  t),
		maximumForce = Mathf.Lerp(a.maximumForce, b.maximumForce, t),
	};
}
